---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up auditd
        run: |
          sudo dnf install -y auditd
          sudo systemctl start auditd
          sudo systemctl enable auditd

      - name: Run check_auditd script tests
        run: |
          chmod +x ./check_auditd
          bash -n ./check_auditd
          #./check_auditd --help

      - name: Run additional tests
        run: |
          sudo ./check_auditd --logins=200,300,0,1000 -v
          sudo ./check_auditd --failedlogins=2,1,0,10 --failedauthentications=10,14,0 -v --ignore faileddogs,failedhounds
          sudo ./check_auditd -a '--auth --failed' -v -n
          sudo ./check_auditd -a '--comm --failed' -A '-x ' -v -n
          sudo ./check_auditd -a '-s --failed' -v -n
