---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
      # TODO: add containers
      # container:
      # image: rockylinux/rockylinux:9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: lint
        run: |
          sudo apt update -y
          sudo apt install -y shellcheck
          shellcheck ./check_auditd

      - name: Syntax check with bash -n
        run: |
          chmod +x ./check_auditd
          bash -n ./check_auditd

      # - name: TODO: run the script, figure out how to make this work
        # run: |
          # systemctl start auditd
          # systemctl enable auditd
          # ./check_auditd --help

      # - name: Run additional tests
        # run: |
          # ./check_auditd --logins=200,300,0,1000 -v
          # ./check_auditd --failedlogins=2,1,0,10 --failedauthentications=10,14,0 -v --ignore faileddogs,failedhounds
          # ./check_auditd -a '--auth --failed' -v -n
          # ./check_auditd -a '--comm --failed' -A '-x ' -v -n
          # ./check_auditd -a '-s --failed' -v -n
